### ISSUE TITLE
datagateway might leave zombie containers behind, blocking forthcoming datagateway requests

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvlabox/management-api#10]

**Comment by mebster** [comment]
After reboot with enabled stream for a USB webcam, the system has several mjpeg streamers:

```
pi@raspberrypi:~ $ sudo docker ps
CONTAINER ID        IMAGE                                         COMMAND                  CREATED             STATUS                        PORTS                      NAMES
c699364baa67        nuvlabox/data-source-mjpg:0.0.1               "./run.sh --input-ty…"   2 minutes ago       Up 48 seconds                                            c5301ef0-1746-42f3-966e-0686e3411d72
5fb4c3415262        nuvlabox/data-source-mjpg:0.0.1               "./run.sh --input-ty…"   2 days ago          Restarting (1) 1 second ago                              bc95398f-580a-4694-87b2-d4b5c8e18ae9
``` 

Disabling the stream again only removes the more recent one.

**Comment by mebster** [comment]
Another time, there is no mjpg container. Unclear.

**Comment by mebster** [comment]
Once enabled, the service keeps on restarting, interfering with other containers attempting to access the same device.  So there's indeed a zombie-like behaviour.

**Comment by cjdcordeiro** [comment]
-> https://github.com/nuvla/api-server/pull/378/files
-> https://github.com/nuvla/job-engine/blob/857c7b51cd5aebb70fca090c7854ba341ad4daef/code/src/nuvla/job/actions/nuvlabox_restart_stream.py#L10

this is why you see 2. the stream is restarted if the usb peripheral changes (like the /dev/video number). But apparently the olf stream is not being killed? need to dig further into the mgmt-api, cause it was supposed to clean up the old one: https://github.com/nuvlabox/management-api/blob/8a9ce005b33df57145c75131edc804f4bdf51f1c/code/app.py#L365 but it didn't...

**Comment by cjdcordeiro** [comment]
protection added in mgmt-api 1.1.1 and syste-manager 1.4.1 - always delete existing mjgp streamers with the same ID, and reap obsolete DG containers
